### ISSUE TITLE
ทดสอบ Colab แปลงร่าง

### ISSUE THREAD

**Issue by mdcu** [md-mutant/R-Manual-for-Sapiens#4]
ผมคิดว่า content เดียวกัน เราควร distribute 3 แบบ

1. Colab = code สลับ คำบรรยาย จะได้ทดลองได้ทันที
2. Static web อาจใช้ markdown ใน github เหมือน colab แต่ไม่ interactive อาจเหมาะกับการอ่าน และทำตามในโปรแรกมตัวเอง
3. pure R code with comments เผื่อบางคนชอบเอาไป run เอง

**ผมขอรับหน้าที่ไปทดลองดูว่า ถ้าเราวาง code ใน Colab แล้วมันแปลงร่างสลับไปมา 3 form นี้ยากง่ายขนาดไหนนะครับ**

_Originally posted by @mdcu in https://github.com/md-mutant/R-Manual-for-Sapiens/issues/2#issuecomment-656483317_

**Comment by mdcu** [comment]
จากการทดลอง 

1. Colab --> save เป็น Jupyter notebook แล้วจาก notebook แปลงเป็น HTML ได้
อย่างไรก็ตาม code เราเป็น R ผมไม่แน่ใจว่า พอแปลงแล้วจะเกิดอะไรขึ้นบ้าง (พอดีผมไม่มี Jupyter ให้ลอง)

2. อย่างไรก็ตามอีกรอบ ... เราเขียนโค้ดไว้โชว์ ไม่ได้ dynamic มาก ถ้าเราทำ version Colab สมบูรณ์แล้ว ทำ version github markdown เพื่อโชว์แบบเว็บด้วยก็ไม่น่ามีปัญหานะครับ
ตัวอย่างเว็บโชว์ code: https://microbiome.github.io/tutorials/Composition.html
@thanonk พี่นน @cchaipat  แบบนี้เค้าทำไงรู้ปะอะ ต้อง manual ไหม หรือ automate ได้ครับ

3. จาก colab แปลงเป็น pure R code ก็ไม่ยาก

**สรุป: ยังมีเรื่องไม่แน่ใจอีกมาก แต่คิดว่า ใช้ Colab เป็นฐานน่าจะไปรอดครับ**

**Comment by cchaipat** [comment]
https://www.youtube.com/watch?v=MsESkSp5cXU

**Comment by thanonk** [comment]
รูปไม่แน่ใจอะ แต่มันน่าจะมาจาก library สักอันของ R  เช่น
https://www.r-graph-gallery.com/
<https://www.r-graph-gallery.com/histogram.html>

**Comment by cchaipat** [comment]
อ้าว ถามเรื่่อง graph หรือฤา

**Comment by mdcu** [comment]
อ่าว จบ แต่ไม่จบ 555
หมายถึงทำให้เป็น html โดยง่ายน่ะครับ

ถ้าทำใน R เอง notebook เรียกว่า RMarkdown อันนี้แปลงเป็น HTML ได้เลย
แต่ถ้าเราดันจะทำใน Colab มันต้องไปแปลงในอีกคำสั่งนึงของ python
